name: Compile 4D Project

on:
  push:
    paths:
      - 'Project/**'
  workflow_dispatch:

env:
  TOOL4D_PATH: C:\Users\Admin\Downloads\tool4d_win\tool4d\Tool4D.exe

jobs:
  checkout:
    name: Checkout Repository
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  compile:
    name: Compile Project with Tool4D
    runs-on: self-hosted
    needs: checkout

    steps:
      - name: Compile with Tool4D
        shell: cmd
        run: |
          %TOOL4D_PATH% --project "C:\Users\Admin\Desktop\demo-Build4D-Win\Project\demo-Build4D-Win.4DProject"  --dataless --log-level=0 --user-param "C:/Users/Admin/Desktop/demo-Build4D-Win/Project/demo-Build4D-Win.4DProject" --skip-onstartup --startup-method "compileMethod" > compile_output.txt

      - name: Upload compilation output
        uses: actions/upload-artifact@v4
        with:
          name: compile-output
          path: compile_output.txt

  analyze:
    name: Analyze Compilation Result
    runs-on: self-hosted
    needs: compile

    steps:
      - name: Download compilation output
        uses: actions/download-artifact@v4
        with:
          name: compile-output
          path: .

      - name: Check compilation result
        run: |
          $content = Get-Content compile_output.txt -Raw
          Write-Output "📄 Tool4D Output:"
          Write-Output $content
          
          if ($content -match '"success"\s*:\s*false' -or $content -match '"errors"\s*:\s*\[[^\]]+') {
              Write-Output "❌ Compilation completed with errors!"
              exit 1
          } else {
              Write-Output "✅ Compilation succeeded with no errors!"
          }
